import { Exercise, Exercises } from "../scripts/Classes/Exercises/Exercises";
import { CourseBase } from "../scripts/Classes/Courses/CourseBase";
import { IExercise } from "../types/types";

export const EXERCISES_TEST: Array<IExercise> = [
	{
		ExecutionTime: 20,
		id: "abs-beginner-01",
		muscleType: "abs",
		name: "Jumping Jacks",
		RepetitionСount: 0,
		lvlDifficulty: { id: 1, name: "Beginner" },
		caloriesBurned: 3,
		description: "ok",
		image: "",
		linkForVideo: "",
	},
	{
		ExecutionTime: 0,
		id: "abs-beginner-02",
		muscleType: "abs",
		name: "Abdominal Crunches",
		RepetitionСount: 16,
		lvlDifficulty: { id: 1, name: "Beginner" },
		caloriesBurned: 3,
		description: "ok",
		image: "",
		linkForVideo: "",
	},
	{
		ExecutionTime: 0,
		id: "abs-beginner-03",
		muscleType: "abs",
		name: "Twist",
		RepetitionСount: 20,
		lvlDifficulty: { id: 1, name: "Beginner" },
		caloriesBurned: 2,
		description: "ok",
		image: "",
		linkForVideo: "",
	},
	{
		ExecutionTime: 0,
		id: "abs-beginner-04",
		muscleType: "abs",
		name: "Mountain Climber",
		RepetitionСount: 16,
		lvlDifficulty: { id: 1, name: "Beginner" },
		caloriesBurned: 4,
		description: "ok",
		image: "",
		linkForVideo: "",
	},
	{
		ExecutionTime: 0,
		id: "abs-beginner-05",
		muscleType: "abs",
		name: "Heel Touch",
		RepetitionСount: 20,
		lvlDifficulty: { id: 1, name: "Beginner" },
		caloriesBurned: 8,
		description: "ok",
		image: "",
		linkForVideo: "",
	},
	{
		ExecutionTime: 0,
		id: "abs-beginner-06",
		muscleType: "abs",
		name: "Leg Raises",
		RepetitionСount: 14,
		lvlDifficulty: { id: 1, name: "Beginner" },
		caloriesBurned: 8,
		description: "ok",
		image: "",
		linkForVideo: "",
	},
	{
		ExecutionTime: 30,
		id: "abs-beginner-07",
		muscleType: "abs",
		name: "Plank",
		RepetitionСount: 0,
		lvlDifficulty: { id: 1, name: "Beginner" },
		caloriesBurned: 3,
		description: "ok",
		image: "",
		linkForVideo: "",
	},
	{
		ExecutionTime: 30,
		id: "abs-beginner-08",
		muscleType: "abs",
		name: "Spine Lumbar Twist Stretch Left",
		RepetitionСount: 0,
		lvlDifficulty: { id: 1, name: "Beginner" },
		caloriesBurned: 3,
		description: "ok",
		image: "",
		linkForVideo: "",
	},
	{
		ExecutionTime: 30,
		id: "abs-beginner-09",
		muscleType: "abs",
		name: "Spine Lumbar Twist Stretch Right",
		RepetitionСount: 0,
		lvlDifficulty: { id: 1, name: "Beginner" },
		caloriesBurned: 3,
		description: "ok",
		image: "",
		linkForVideo: "",
	},
	{
		ExecutionTime: 30,
		id: "abs-beginner-10",
		muscleType: "abs",
		name: "Cobra Stretch",
		RepetitionСount: 0,
		lvlDifficulty: { id: 1, name: "Beginner" },
		caloriesBurned: 2,
		description: "ok",
		image: "",
		linkForVideo: "",
	},
];

export const EXERCISES_LIST_TEST = new Exercises();

EXERCISES_TEST.forEach((element: any) => {
	EXERCISES_LIST_TEST.pushExercise(new Exercise(element));
});
export const ABSCourseTEST1 = new CourseBase({
	name: "ABS Beginner",
	muscleZone: "Abs",
	exercises: EXERCISES_LIST_TEST.getExercises,
	lvlDifficulty: 1,
	id: "123456767889test_course",
	lastTimeExecution: new Date().toLocaleString(),
	isCreateByUser: {state:false,userId:null},
	isUserFollow: false,
	image: "",
});

export const ABSCourseTEST2 = new CourseBase({
	name: "ABS Beginner2",
	muscleZone: "Abs",
	exercises: [],
	lvlDifficulty: 2,
	id: "123456767889test_courseasdasd",
	lastTimeExecution: new Date().toLocaleString(),
	isCreateByUser: {state:false,userId:null},
	isUserFollow: false,
	image: "",
});
